export const PUT__EXISTING_SUPPORTER_INTO_STATE = 'PUT__EXISTING_SUPPORTER_INTO_STATE';
export const EXISTING_SUPPORTER__NEXT = 'EXIStING_SUPPORTER__NEXT';
export const EXISTING_SUPPORTER__BACK = 'EXIStING_SUPPORTER__BACK';

export const PUT__APPLICANT_EMAIL_INTO_STATE = 'PUT__APPLICANT_EMAIL_INTO_STATE';
export const APPLICANT_EMAIL__NEXT = 'APPLICANT_EMAIL__NEXT';
export const APPLICANT_EMAIL__BACK = 'APPLICANT_EMAIL__BACK';

export const PUT__APPLICANT_NAME_INTO_STATE = 'PUT__APPLICANT_NAME_INTO_STATE';
export const APPLICANT_NAME__NEXT = 'APPLICANT_NAME__NEXT';
export const APPLICANT_NAME__BACK = 'APPLICANT_NAME__BACK';

export const PUT__APPLICANT_PHONE_NOS_INTO_STATE = 'PUT__APPLICANT_PHONE_NOS_INTO_STATE';
export const APPLICANT_PHONE_NOS__NEXT = 'APPLICANT_PHONE_NOS__NEXT';
export const APPLICANT_PHONE_NOS__BACK = 'APPLICANT_PHONE_NOS__BACK';

export const PUT__SUPPORTER_EXPERIENCE_INTO_STATE = 'PUT__SUPPORTER_EXPERIENCE_INTO_STATE';
export const SUPPORTER_EXPERIENCE__NEXT = 'SUPPORTER_EXPERIENCE__NEXT';
export const SUPPORTER_EXPERIENCE__BACK = 'SUPPORTER_EXPERIENCE__BACK';
