export const PUT__EXISTING_SUPPORTER_INTO_STATE = 'PUT__EXISTING_SUPPORTER_INTO_STATE';
export const EXISTING_SUPPORTER__NEXT = 'EXIStING_SUPPORTER__NEXT';
export const EXISTING_SUPPORTER__BACK = 'EXIStING_SUPPORTER__NEXT';

